name: python36
channels:
dependencies:
   - python=3.6
   - pytorch
   - torchvision
   - opencv
   - tqdm
   - scipy
   - pip:
     - wandb
       #- "--editable=git+https://github.com/mshafiei/cvgutils/tree/master"
