name: python37
channels:
dependencies:
   - python=3.7
   - pytorch=1.5.0
   - torchvision
   - opencv
   - tqdm
   - scipy
   - pip:
     - wandb
     - pytorch3d
       #- "--editable=git+https://github.com/mshafiei/cvgutils/tree/master"
