name: python37
channels:
        - conda-forge
        - pytorch
dependencies:
   - python=3.7
   - pytorch=1.5.0
   - torchvision
   - openexr   
   - opencv
   - openexr-python
   - tqdm
   - scipy
   - pip:
     - wandb
     - pytorch3d
       #- "--editable=git+https://github.com/mshafiei/cvgutils/tree/master"
